package com.example.Student_Library_Management_System.Services;


import com.example.Student_Library_Management_System.Enums.CardStatus;
import com.example.Student_Library_Management_System.Models.Card;
import com.example.Student_Library_Management_System.Models.Student;
import com.example.Student_Library_Management_System.Repositories.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class StudentService {


    @Autowired
    StudentRepository studentRepository;

    public String createStudent(Student student)
    {
        //student from the postman is already having the basic attribute set

        //card should be autogenerated when create student function is called.
        Card card=new Card();
        card.setCardStatus(CardStatus.ACTIVATED);
        card.setStudentVariableName(student);

        student.setCard(card);

        //if there was a unidirectional mapping we have to save both of them

        //but we are super advance we are using bidirectional mapping, child will automatically save

        studentRepository.save(student);

        //by cascading effect child will automaticaally be saved.
        return "Student and card added";
    }
}
